### Assign each tweet a stock price on a specific date which is the closest available date right after the date when the tweet is posted, such as assigning tweets posted on 12/24, 12/25, and 12/26 the stock price of 12/27.

In [1]:
import pandas as pd

tweets_df = pd.read_csv('output.csv')

In [2]:
tweets_df

,Unnamed: 0,Date,Tweet,Clean_Tweet,Negative,Neutral,Positive,Sentiment
0,0,2023-03-19 23:59:54+00:00,"Oh my god, the South Park episode about ChatGP...","Oh my god, the South Park episode about ChatGP...",0.002614,0.010037,0.987349,1
1,1,2023-03-19 23:59:36+00:00,Bing powered by #chatgpt is a new way of learn...,Bing powered by #chatgpt is a new way of learn...,0.001523,0.061577,0.936899,1
2,2,2023-03-19 23:59:04+00:00,yall need to start using chatGPT to improve yo...,yall need to start using chatGPT to improve yo...,0.044139,0.216546,0.739315,1
3,3,2023-03-19 23:58:52+00:00,Chat GPT and Twitter Blue stops me from saying...,Chat GPT and Twitter Blue stops me from saying...,0.103467,0.325155,0.571378,1
4,4,2023-03-19 23:58:49+00:00,chat gpt is insane it’s gonna change how ppl d...,chat gpt is insane it’s gonna change how ppl d...,0.116454,0.427531,0.456015,1
...,...,...,...,...,...,...,...,...
296378,296378,2022-12-01 00:14:08+00:00,#ChatGPT from @OpenAI looks extremely promisin...,#ChatGPT from @user looks extremely promising!...,0.001137,0.006888,0.991975,1
296379,296379,2022-12-01 00:08:07+00:00,Me: Henry is a fish that got eaten by a cat ca...,Me: Henry is a fish that got eaten by a cat ca...,0.310093,0.618012,0.071895,0
296380,296380,2022-12-01 00:05:27+00:00,"Long day of meetings, then you open Twitter an...","Long day of meetings, then you open Twitter an...",0.661903,0.283301,0.054796,-1
296381,296381,2022-12-01 00:02:43+00:00,Me: Can you give me a sensationalist headline ...,Me: Can you give me a sensationalist headline ...,0.245476,0.606909,0.147615,0
296382,296382,2022-12-01 00:00:28+00:00,chatgpt is really cool but man saying shit to ...,chatgpt is really cool but man saying shit to ...,0.643117,0.273827,0.083056,-1

In [3]:
stocks_df = pd.read_csv('MSFT.csv')

In [4]:
stocks_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2022-12-01,253.869995,256.119995,250.919998,254.690002,254.053665,26041500
1,2022-12-02,249.820007,256.059998,249.690002,255.020004,254.382843,21528500
2,2022-12-05,252.009995,253.820007,248.059998,250.199997,249.574890,23435300
3,2022-12-06,250.820007,251.860001,243.779999,245.119995,244.507568,22463700
4,2022-12-07,244.830002,246.160004,242.210007,244.369995,243.759445,20481500
...,...,...,...,...,...,...,...
69,2023-03-14,256.750000,261.070007,255.860001,260.790009,260.790009,33620300
70,2023-03-15,259.980011,266.480011,259.209991,265.440002,265.440002,46028000
71,2023-03-16,265.209991,276.559998,263.279999,276.200012,276.200012,54768800
72,2023-03-17,278.260010,283.329987,276.320007,279.429993,279.429993,69527400
73,2023-03-20,276.980011,277.480011,269.850006,272.230011,272.230011,43466600

In [5]:
# Transform the column "Date" to type "datetime" with format YYYY-MM-DD using pandas and store it as a new column "timestamp" to the end of tweets_df
tweets_df['tweet_date'] = pd.to_datetime(tweets_df['Date']).dt.date

In [6]:
tweets_df['tweet_date'] = pd.to_datetime(tweets_df['tweet_date'])

In [7]:
tweets_df

,Unnamed: 0,Date,Tweet,Clean_Tweet,Negative,Neutral,Positive,Sentiment,tweet_date
0,0,2023-03-19 23:59:54+00:00,"Oh my god, the South Park episode about ChatGP...","Oh my god, the South Park episode about ChatGP...",0.002614,0.010037,0.987349,1,2023-03-19
1,1,2023-03-19 23:59:36+00:00,Bing powered by #chatgpt is a new way of learn...,Bing powered by #chatgpt is a new way of learn...,0.001523,0.061577,0.936899,1,2023-03-19
2,2,2023-03-19 23:59:04+00:00,yall need to start using chatGPT to improve yo...,yall need to start using chatGPT to improve yo...,0.044139,0.216546,0.739315,1,2023-03-19
3,3,2023-03-19 23:58:52+00:00,Chat GPT and Twitter Blue stops me from saying...,Chat GPT and Twitter Blue stops me from saying...,0.103467,0.325155,0.571378,1,2023-03-19
4,4,2023-03-19 23:58:49+00:00,chat gpt is insane it’s gonna change how ppl d...,chat gpt is insane it’s gonna change how ppl d...,0.116454,0.427531,0.456015,1,2023-03-19
...,...,...,...,...,...,...,...,...,...
296378,296378,2022-12-01 00:14:08+00:00,#ChatGPT from @OpenAI looks extremely promisin...,#ChatGPT from @user looks extremely promising!...,0.001137,0.006888,0.991975,1,2022-12-01
296379,296379,2022-12-01 00:08:07+00:00,Me: Henry is a fish that got eaten by a cat ca...,Me: Henry is a fish that got eaten by a cat ca...,0.310093,0.618012,0.071895,0,2022-12-01
296380,296380,2022-12-01 00:05:27+00:00,"Long day of meetings, then you open Twitter an...","Long day of meetings, then you open Twitter an...",0.661903,0.283301,0.054796,-1,2022-12-01
296381,296381,2022-12-01 00:02:43+00:00,Me: Can you give me a sensationalist headline ...,Me: Can you give me a sensationalist headline ...,0.245476,0.606909,0.147615,0,2022-12-01
296382,296382,2022-12-01 00:00:28+00:00,chatgpt is really cool but man saying shit to ...,chatgpt is really cool but man saying shit to ...,0.643117,0.273827,0.083056,-1,2022-12-01

In [8]:
# Transform the column "Date" to type "datetime" using pandas and store it as a new column "date" to the end of stocks_df
stocks_df['stock_date'] = pd.to_datetime(stocks_df['Date'])

In [9]:
stocks_df = stocks_df.drop('Date', axis=1)

In [10]:
stocks_df

,Open,High,Low,Close,Adj Close,Volume,stock_date
0,253.869995,256.119995,250.919998,254.690002,254.053665,26041500,2022-12-01
1,249.820007,256.059998,249.690002,255.020004,254.382843,21528500,2022-12-02
2,252.009995,253.820007,248.059998,250.199997,249.574890,23435300,2022-12-05
3,250.820007,251.860001,243.779999,245.119995,244.507568,22463700,2022-12-06
4,244.830002,246.160004,242.210007,244.369995,243.759445,20481500,2022-12-07
...,...,...,...,...,...,...,...
69,256.750000,261.070007,255.860001,260.790009,260.790009,33620300,2023-03-14
70,259.980011,266.480011,259.209991,265.440002,265.440002,46028000,2023-03-15
71,265.209991,276.559998,263.279999,276.200012,276.200012,54768800,2023-03-16
72,278.260010,283.329987,276.320007,279.429993,279.429993,69527400,2023-03-17
73,276.980011,277.480011,269.850006,272.230011,272.230011,43466600,2023-03-20

In [11]:
tweets_df = tweets_df.drop('Unnamed: 0', axis=1)

In [12]:
tweets_df = tweets_df.reset_index()

In [13]:
tweets_df

,index,Date,Tweet,Clean_Tweet,Negative,Neutral,Positive,Sentiment,tweet_date
0,0,2023-03-19 23:59:54+00:00,"Oh my god, the South Park episode about ChatGP...","Oh my god, the South Park episode about ChatGP...",0.002614,0.010037,0.987349,1,2023-03-19
1,1,2023-03-19 23:59:36+00:00,Bing powered by #chatgpt is a new way of learn...,Bing powered by #chatgpt is a new way of learn...,0.001523,0.061577,0.936899,1,2023-03-19
2,2,2023-03-19 23:59:04+00:00,yall need to start using chatGPT to improve yo...,yall need to start using chatGPT to improve yo...,0.044139,0.216546,0.739315,1,2023-03-19
3,3,2023-03-19 23:58:52+00:00,Chat GPT and Twitter Blue stops me from saying...,Chat GPT and Twitter Blue stops me from saying...,0.103467,0.325155,0.571378,1,2023-03-19
4,4,2023-03-19 23:58:49+00:00,chat gpt is insane it’s gonna change how ppl d...,chat gpt is insane it’s gonna change how ppl d...,0.116454,0.427531,0.456015,1,2023-03-19
...,...,...,...,...,...,...,...,...,...
296378,296378,2022-12-01 00:14:08+00:00,#ChatGPT from @OpenAI looks extremely promisin...,#ChatGPT from @user looks extremely promising!...,0.001137,0.006888,0.991975,1,2022-12-01
296379,296379,2022-12-01 00:08:07+00:00,Me: Henry is a fish that got eaten by a cat ca...,Me: Henry is a fish that got eaten by a cat ca...,0.310093,0.618012,0.071895,0,2022-12-01
296380,296380,2022-12-01 00:05:27+00:00,"Long day of meetings, then you open Twitter an...","Long day of meetings, then you open Twitter an...",0.661903,0.283301,0.054796,-1,2022-12-01
296381,296381,2022-12-01 00:02:43+00:00,Me: Can you give me a sensationalist headline ...,Me: Can you give me a sensationalist headline ...,0.245476,0.606909,0.147615,0,2022-12-01
296382,296382,2022-12-01 00:00:28+00:00,chatgpt is really cool but man saying shit to ...,chatgpt is really cool but man saying shit to ...,0.643117,0.273827,0.083056,-1,2022-12-01

In [14]:
tweets_df.head()

,index,Date,Tweet,Clean_Tweet,Negative,Neutral,Positive,Sentiment,tweet_date
0,0,2023-03-19 23:59:54+00:00,"Oh my god, the South Park episode about ChatGP...","Oh my god, the South Park episode about ChatGP...",0.002614,0.010037,0.987349,1,2023-03-19
1,1,2023-03-19 23:59:36+00:00,Bing powered by #chatgpt is a new way of learn...,Bing powered by #chatgpt is a new way of learn...,0.001523,0.061577,0.936899,1,2023-03-19
2,2,2023-03-19 23:59:04+00:00,yall need to start using chatGPT to improve yo...,yall need to start using chatGPT to improve yo...,0.044139,0.216546,0.739315,1,2023-03-19
3,3,2023-03-19 23:58:52+00:00,Chat GPT and Twitter Blue stops me from saying...,Chat GPT and Twitter Blue stops me from saying...,0.103467,0.325155,0.571378,1,2023-03-19
4,4,2023-03-19 23:58:49+00:00,chat gpt is insane it’s gonna change how ppl d...,chat gpt is insane it’s gonna change how ppl d...,0.116454,0.427531,0.456015,1,2023-03-19

In [15]:
# create a column with same value "dummy" for both dataframes to enforce cross join on "tweets" and "stockp_price"
tweets_df['cross_join_key'] = 'dummy'
stocks_df['cross_join_key'] = 'dummy'

In [16]:
# Cross join two dataframes using the same dummy key "cross_join_key"
merged_df = tweets_df.merge(stocks_df, on='cross_join_key', how='outer')

In [17]:
merged_df.shape

(21932342, 17)

In [18]:
merged_df.groupby('index').size().describe()

count    296383.0
mean         74.0
std           0.0
min          74.0
25%          74.0
50%          74.0
75%          74.0
max          74.0
dtype: float64

In [19]:
# filter the qualified rows where the stock price is the future stock price for each tweet
# where "stock_date" is date of stock price date while "tweet_date" is date of tweet
merged_df = merged_df[merged_df['stock_date'] > merged_df['tweet_date']]

In [21]:
merged_df = merged_df.sort_values(['index', 'stock_date'])

In [22]:
# only retain the closest available future stock price
merged_df = merged_df.groupby('index').head(1)

In [23]:
merged_df.groupby('tweet_date').head(1).head(20)

,index,Date,Tweet,Clean_Tweet,Negative,Neutral,Positive,Sentiment,tweet_date,cross_join_key,Open,High,Low,Close,Adj Close,Volume,stock_date
73,0,2023-03-19 23:59:54+00:00,"Oh my god, the South Park episode about ChatGP...","Oh my god, the South Park episode about ChatGP...",0.002614,0.010037,0.987349,1,2023-03-19,dummy,276.980011,277.480011,269.850006,272.230011,272.230011,43466600,2023-03-20
315905,4268,2023-03-18 23:59:52+00:00,I've been using chatgpt for 5 minutes and it's...,I've been using chatgpt for 5 minutes and it's...,0.002701,0.061290,0.936009,1,2023-03-18,dummy,276.980011,277.480011,269.850006,272.230011,272.230011,43466600,2023-03-20
660745,8928,2023-03-17 23:59:52+00:00,ChatGTP (GPT-4) will be used to write fake pro...,ChatGTP (GPT-4) will be used to write fake pro...,0.722613,0.265609,0.011779,-1,2023-03-17,dummy,276.980011,277.480011,269.850006,272.230011,272.230011,43466600,2023-03-20
1118804,15118,2023-03-16 23:59:35+00:00,ChatGPT reminds me of Derrida’s wisdom about d...,ChatGPT reminds me of Derrida’s wisdom about d...,0.255540,0.647598,0.096862,0,2023-03-16,dummy,278.260010,283.329987,276.320007,279.429993,279.429993,69527400,2023-03-17
1392529,18817,2023-03-15 23:59:59+00:00,Greasing human interactions is the best use of...,Greasing human interactions is the best use of...,0.421540,0.471986,0.106474,0,2023-03-15,dummy,265.209991,276.559998,263.279999,276.200012,276.200012,54768800,2023-03-16
2115508,28587,2023-03-14 23:59:53+00:00,If you're autistic you can just tell GPT to pr...,If you're autistic you can just tell GPT to pr...,0.379119,0.562351,0.058530,0,2023-03-14,dummy,259.980011,266.480011,259.209991,265.440002,265.440002,46028000,2023-03-15
2604795,35199,2023-03-13 23:59:59+00:00,The Case For AI In Construction 🤨\n\nRead more...,The Case For AI In Construction 🤨\n\nRead more...,0.013155,0.410306,0.576539,1,2023-03-13,dummy,256.750000,261.070007,255.860001,260.790009,260.790009,33620300,2023-03-14
2808960,37958,2023-03-12 23:59:51+00:00,Hmm chat GPT is actually very valid,Hmm chat GPT is actually very valid,0.009356,0.146624,0.844020,1,2023-03-12,dummy,247.399994,257.910004,245.729996,253.919998,253.919998,33339700,2023-03-13
2977458,40235,2023-03-11 23:58:22+00:00,I'm finding ChatGPT much more helpful than Goo...,I'm finding ChatGPT much more helpful than Goo...,0.014723,0.117384,0.867893,1,2023-03-11,dummy,247.399994,257.910004,245.729996,253.919998,253.919998,33339700,2023-03-13
3165418,42775,2023-03-10 23:59:43+00:00,Why tf didn't ChatGPT warn me about all this b...,Why tf didn't ChatGPT warn me about all this b...,0.892364,0.100600,0.007037,-1,2023-03-10,dummy,247.399994,257.910004,245.729996,253.919998,253.919998,33339700,2023-03-13
3422937,46255,2023-03-09 23:59:57+00:00,"chatGPT\n\nthere is no there, there","chatGPT\n\nthere is no there, there",0.309496,0.639315,0.051189,0,2023-03-09,dummy,251.080002,252.789993,247.600006,248.589996,248.589996,28333900,2023-03-10
3690520,49871,2023-03-08 23:59:54+00:00,Is ChatGPT Dead? AI Tools and the Hype Cycle #...,Is ChatGPT Dead? AI Tools and the Hype Cycle #...,0.317176,0.628440,0.054383,0,2023-03-08,dummy,255.820007,259.559998,251.580002,252.320007,252.320007,26653400,2023-03-09
3945819,53321,2023-03-07 23:59:56+00:00,Good god I am repetitive in first drafts. I am...,Good god I am repetitive in first drafts. I am...,0.612935,0.314503,0.072561,-1,2023-03-07,dummy,254.039993,254.539993,250.809998,253.699997,253.699997,17340200,2023-03-08
4142658,55981,2023-03-06 23:58:44+00:00,OpenAI's GPT-3 language model is incredibly po...,OpenAI's GPT-3 language model is incredibly po...,0.013604,0.121009,0.865387,1,2023-03-06,dummy,256.299988,257.690002,253.389999,254.149994,254.149994,21473200,2023-03-07
4327065,58473,2023-03-05 23:59:18+00:00,Seems like LLMs/chatgpt are more platform shif...,Seems like LLMs/chatgpt are more platform shif...,0.577100,0.367579,0.055321,-1,2023-03-05,dummy,256.429993,260.119995,255.979996,256.869995,256.869995,24109800,2023-03-06
4406097,59541,2023-03-04 23:59:17+00:00,Bit more than 24 hours into my challenge of us...,Bit more than 24 hours into my challenge of us...,0.006733,0.083928,0.909340,1,2023-03-04,dummy,256.429993,260.119995,255.979996,256.869995,256.869995,24109800,2023-03-06
4566307,61706,2023-03-03 23:59:01+00:00,"I daily hope to meet someone named, Chad, so I...","I daily hope to meet someone named, Chad, so I...",0.002539,0.067368,0.930093,1,2023-03-03,dummy,256.429993,260.119995,255.979996,256.869995,256.869995,24109800,2023-03-06
4770546,64466,2023-03-02 23:59:56+00:00,I just put all my journals inside chatGPT API ...,I just put all my journals inside chatGPT API ...,0.047808,0.270380,0.681812,1,2023-03-02,dummy,252.190002,255.619995,251.389999,255.289993,255.289993,30760100,2023-03-03
5018815,67821,2023-03-01 23:59:47+00:00,So now that Open AIs ChatGPT is available via ...,So now that Open AIs ChatGPT is available via ...,0.015950,0.361538,0.622512,1,2023-03-01,dummy,246.550003,251.399994,245.610001,251.110001,251.110001,24808200,2023-03-02
5125448,69262,2023-02-28 23:58:59+00:00,This is a chat gpt response.,This is a chat gpt response.,0.087759,0.849642,0.062599,0,2023-02-28,dummy,250.759995,250.929993,245.789993,246.270004,246.270004,27565300,2023-03-01

In [24]:
merged_df.to_csv('merged_tweets_and_stock_prices.csv', index=False)